backend/src/main/java/com/hot6/backend/common/BaseResponse.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/common/exception/BaseException.java, backend/src/main/java/com/hot6/backend/common/exception/GlobalExceptionHandler.java
=> [Feat] 공통 코드 작성 (#9)

backend/src/main/java/com/hot6/backend/user/UserRepository.java, backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java, backend/src/main/java/com/hot6/backend/user/model/UserType.java
=> [Feat] 회원 로그인 기능 작성 (#4)

backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/config/WebSocketConfig.java, backend/src/main/java/com/hot6/backend/config/filter/JwtChannelInterceptor.java, backend/src/main/java/com/hot6/backend/config/filter/JwtHandshakeInterceptor.java
=> [Feat] websocket + Jwt 채팅 기능 (#13)

backend/.gitignore, backend/build.gradle, backend/src/main/java/com/hot6/backend/config/SecurityConfig.java, backend/src/main/java/com/hot6/backend/config/filter/LoginFilter.java, backend/src/main/java/com/hot6/backend/user/KakaoOAuth2UserService.java, backend/src/main/java/com/hot6/backend/user/UserController.java, backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java, backend/src/main/resources/application.yml
=> [Feat] 로그인 체크 구현, 카카오 로그인 구현 중

backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/Chat.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoom.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoomHashtag.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoomParticipant.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRepository.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomHashtagRepository.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomParticipantRepository.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepository.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomHashtagService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java, backend/src/main/java/com/hot6/backend/user/model/User.java
=> [Feat] 전체 채팅방 조회 기능 작성 (#69)

backend/src/main/java/com/hot6/backend/config/WebConfig.java, backend/src/main/java/com/hot6/backend/pet/ImageService.java, backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/pet/PetImageService.java, backend/src/main/java/com/hot6/backend/pet/PetRepository.java, backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/model/Pet.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java, backend/src/main/java/com/hot6/backend/pet/model/PetImage.java, backend/src/main/resources/application.yml
=> [Feat] mypage 개발

backend/src/main/java/com/hot6/backend/board/post/BoardTypeRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/BoardType.java, backend/src/main/java/com/hot6/backend/board/post/model/Post.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java
=> [Feat] 자유, 정보 공유 게시판 구현, 조회/생성 기능 구현

backend/src/main/java/com/hot6/backend/board/post/BoardTypeRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/BoardType.java
=> [Feat] 게시판 종류 엔티티 생성 및 연관관계 매핑

backend/build.gradle, backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
=> [Fix] mypage 수정

backend/src/main/java/com/hot6/backend/board/answer/AnswerController.java, backend/src/main/java/com/hot6/backend/board/hashtagQuestion/Hashtag_QuestionController.java, backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java
=> [Fix] 컨트롤러 경로 수정

backend/src/main/java/com/hot6/backend/board/comment/CommentController.java, backend/src/main/java/com/hot6/backend/board/comment/CommentRepository.java, backend/src/main/java/com/hot6/backend/board/comment/CommentService.java, backend/src/main/java/com/hot6/backend/board/comment/model/Comment.java, backend/src/main/java/com/hot6/backend/board/comment/model/CommentDto.java
=> [Feat] 일반 게시글 댓글 기능 구현

backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
=> [Fix] 중성화 표시 수정

backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/hashtagQuestion/Hashtag_QuestionRepository.java, backend/src/main/java/com/hot6/backend/board/hashtagQuestion/Hashtag_QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
질문 수정/삭제 기능 구현
close #53 
close #54
=> [Feat] 질문 수정/삭제 기능 구현

backend/src/main/resources/application.yml, backend/src/main/resources/data.sql
=> [Feat] data.sql 파일 추가

backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomHashtagService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomParticipantService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/user/UserRepository.java, backend/src/main/java/com/hot6/backend/user/UserService.java
=> [Feat] 채팅방 생성 기능 (#14)

backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomParticipantRepositoryCustom.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomParticipantRepositoryImpl.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomParticipantService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java
N + 1 문제 해결(query dsl + join), Slice 적용
=> [Feat] 채팅방에 참여한 유저 목록 조회 기능 (#93)

backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/model/Pet.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java, backend/src/main/java/com/hot6/backend/pet/model/PetStatus.java
=> [Feat] 반려동물 카드 수정

backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
=> [Fix] 반려동물 DTO 수정

backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
=> [Fix] 반려동물 기능 수정

backend/build.gradle, backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoomParticipant.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoomUserMetaData.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatMessageRepository.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomParticipantRepository.java, backend/src/main/java/com/hot6/backend/chat/service/ChatMessageService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomParticipantService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
- ChatRoomParticipant.metaData의 firstJoinMessageId 기반으로 메시지 조회 범위 제한
- ChatMessageRepository에 JPQL 기반 쿼리 추가
close #20
=> [Feat] 채팅방 메시지 조회 기능(#20)

backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/java/com/hot6/backend/user/model/CustomOAuth2User.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java
=> [Fix] oauth2 토큰에 idx 추가

backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/comment/model/CommentDto.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java
=> [Feat] 총 답변 수 표시

backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/Chat.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepository.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java
=> [Feat] 채팅방내 채팅방 정보 조회(#93)

backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/user/UserController.java, backend/src/main/java/com/hot6/backend/user/UserService.java
=> [Feat] 유저 연동 마이페이지 프로필, 펫카드

backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/S3Service.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
=> [Feat] AWS S3 업로드 기능 추가

backend/src/main/java/com/hot6/backend/chat/ChatWebSocketController.java, backend/src/main/java/com/hot6/backend/chat/model/Chat.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/model/ChatMessageType.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepository.java, backend/src/main/java/com/hot6/backend/chat/service/ChatMessageService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java, backend/src/main/java/com/hot6/backend/config/SecurityConfig.java
동기식으로 저장
DB 로 채팅방 및 채팅방 참여 유저 조회 -> DB 저장 -> sub 한 사용자에게 전송
=> [Feat] 채팅 내용 저장 및 전송된 내용 구독한 사용자들에게 전송 (#113)

backend/src/main/java/com/hot6/backend/user/UserController.java, backend/src/main/java/com/hot6/backend/user/UserService.java
=> [Fix] 프로필 사진 수정

backend/src/main/java/com/hot6/backend/board/comment/CommentController.java, backend/src/main/java/com/hot6/backend/board/comment/CommentService.java, backend/src/main/java/com/hot6/backend/board/comment/model/CommentDto.java
=> [Fix] 댓글 기능 수정

backend/src/main/java/com/hot6/backend/board/answer/AnswerController.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/answer/model/AnswerDto.java
=> [Fix] 답변 조회 기능

backend/src/main/java/com/hot6/backend/board/answer/AnswerController.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/answer/images/AnswerImage.java, backend/src/main/java/com/hot6/backend/board/answer/images/AnswerImageRepository.java, backend/src/main/java/com/hot6/backend/board/answer/images/AnswerImageService.java, backend/src/main/java/com/hot6/backend/board/answer/model/Answer.java, backend/src/main/java/com/hot6/backend/board/answer/model/AnswerDto.java, backend/src/main/java/com/hot6/backend/board/comment/CommentRepository.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/images/QuestionImage.java, backend/src/main/java/com/hot6/backend/board/question/images/QuestionImageRepository.java, backend/src/main/java/com/hot6/backend/board/question/images/QuestionImageService.java, backend/src/main/java/com/hot6/backend/board/question/model/Question.java, backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java, backend/src/main/resources/application.yml, backend/src/main/resources/data.sql
Q&A 게시판 이미지 업로드 기능 구현
close #119
=> [Feat] Q&A 게시판 이미지 업로드 기능 구현

backend/src/main/java/com/hot6/backend/config/filter/JwtFilter.java, backend/src/main/java/com/hot6/backend/user/CustomOAuth2UserService.java, backend/src/main/java/com/hot6/backend/user/model/User.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java
=> [Feat] provider 추가

backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoom.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepository.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepositoryCustom.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepositoryImpl.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java
=> [Feat] 무한 스크롤을 위한 채팅방 목록 조회 기능(#91,#69)

backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/images/PostImage.java, backend/src/main/java/com/hot6/backend/board/post/images/PostImageRepository.java, backend/src/main/java/com/hot6/backend/board/post/images/PostImageService.java, backend/src/main/java/com/hot6/backend/board/post/model/Post.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java
=> [Feat] 게시글 이미지 업로드 기능 구현

backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/images/PostImageService.java, backend/src/main/java/com/hot6/backend/pet/S3Service.java
=> [Feat] 게시글 이미지 수정/삭제

backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/images/QuestionImageService.java
=> [Feat] 질문 이미지 수정/삭제

backend/src/main/java/com/hot6/backend/board/answer/model/AnswerDto.java, backend/src/main/java/com/hot6/backend/board/comment/model/CommentDto.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java, backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java, backend/src/main/resources/application.yml, backend/src/main/resources/data.sql
=> [Feat] User 프로필 이미지 게시판 연동

backend/src/main/java/com/hot6/backend/category/CategoryController.java, backend/src/main/java/com/hot6/backend/category/CategoryService.java, backend/src/main/java/com/hot6/backend/category/model/Category.java, backend/src/main/java/com/hot6/backend/category/model/CategoryDto.java, backend/src/main/java/com/hot6/backend/category/model/CategoryRepository.java, backend/src/main/java/com/hot6/backend/category/model/CategoryType.java
=> [Feat] 카테고리 기능

backend/build.gradle, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/answer/aiAnswer/AiAnswerService.java, backend/src/main/java/com/hot6/backend/board/answer/model/Answer.java, backend/src/main/java/com/hot6/backend/board/answer/model/AnswerDto.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/user/UserRepository.java, backend/src/main/java/com/hot6/backend/user/model/User.java, backend/src/main/java/com/hot6/backend/user/model/UserType.java, backend/src/main/resources/application.yml
=> [Feat] Ai 답변 기능 구현

backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/Post.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/category/model/Category.java
=> [Fix] 카테고리 기능 강화

backend/src/main/java/com/hot6/backend/board/answer/AnswerController.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java, backend/src/main/java/com/hot6/backend/category/model/Category.java, backend/src/main/resources/data.sql
=> [fix] Ai 답변 수정

backend/src/main/java/com/hot6/backend/pet/model/Pet.java, backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java
=> [Fix] 반려동물 삭제 오류 해결

backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
=> [Fix] 펫 카드 수정기능

backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
=> [Fix] 최종 펫 카드 수정 오류 해결

backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/SharedSchedulePetRepository.java, backend/src/main/java/com/hot6/backend/pet/SharedSchedulePetService.java
=> [Feat] 채팅방 일정 참여 기능 (#149)

backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/pet/model/Pet.java, backend/src/main/java/com/hot6/backend/record/DailyRecordController.java, backend/src/main/java/com/hot6/backend/record/DailyRecordRepository.java, backend/src/main/java/com/hot6/backend/record/DailyRecordService.java, backend/src/main/java/com/hot6/backend/record/model/DailyRecord.java, backend/src/main/java/com/hot6/backend/record/model/DailyRecordDto.java, backend/src/main/resources/application.yml, backend/src/main/resources/data.sql
- 기록 생성 기능
- 날짜별 기록 조회 기능
close #29
=> [Feat] 기록 생성 기능, 날짜별 기록 조회 기능 구현 (#29, #24)

backend/src/main/java/com/hot6/backend/notification/NotificationController.java, backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java, backend/src/main/java/com/hot6/backend/notification/NotificationService.java, backend/src/main/java/com/hot6/backend/notification/model/Notification.java, backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java, backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java
=> [Feat] 알림 기능 미완성

backend/src/main/java/com/hot6/backend/InitDB.java, backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/Post.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionRepository.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/model/Question.java, backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java, backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java, backend/src/main/java/com/hot6/backend/notification/NotificationService.java, backend/src/main/java/com/hot6/backend/pet/PetRepository.java, backend/src/main/java/com/hot6/backend/pet/model/Pet.java, backend/src/main/java/com/hot6/backend/pet/model/PetSummary.java, backend/src/main/resources/application.yml
게시판 반려동물 카드 등록 기능 구현, 알림 관련 수정
close #138
=> [Feat] 게시판 반려동물 카드 등록 기능 구현, 알림 관련 수정

backend/src/main/java/com/hot6/backend/InitDB.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/images/PostImageRepository.java, backend/src/main/java/com/hot6/backend/board/post/images/PostImageService.java, backend/src/main/java/com/hot6/backend/board/post/model/Post.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/images/QuestionImageRepository.java, backend/src/main/java/com/hot6/backend/board/question/images/QuestionImageService.java, backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java
게시판 반려동물 카드 수정/삭제 기능 구현
close #140 
close #139
=> [Feat] 게시판 반려동물 카드 수정/삭제 기능 구현

backend/src/main/java/com/hot6/backend/InitDB.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerController.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/answer/images/AnswerImageRepository.java, backend/src/main/java/com/hot6/backend/board/answer/images/AnswerImageService.java, backend/src/main/java/com/hot6/backend/board/answer/model/AnswerDto.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java
=> [Fix] Q&A 게시판 답변 기능 수정

backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionRepository.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
=> [Feat] 게시판 페이징 처리

backend/src/main/java/com/hot6/backend/BackendApplication.java, backend/src/main/java/com/hot6/backend/notification/NotificationService.java, backend/src/main/java/com/hot6/backend/notification/ScheduleNotificationScheduler.java, backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java, backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java
=> [Feat] 알림 1시간전에 오게 하기

backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionRepository.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
=> [Feat] 게시판 검색 기능 페이징 처리

backend/src/main/java/com/hot6/backend/InitDB.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/record/DailyRecordController.java, backend/src/main/java/com/hot6/backend/record/DailyRecordRepository.java, backend/src/main/java/com/hot6/backend/record/DailyRecordService.java, backend/src/main/java/com/hot6/backend/record/model/DailyRecordDto.java, backend/src/main/java/com/hot6/backend/schedule/ScheduleController.java, backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java, backend/src/main/java/com/hot6/backend/schedule/ScheduleService.java, backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java, backend/src/main/java/com/hot6/backend/schedule/model/ScheduleDto.java, backend/src/main/java/com/hot6/backend/user/model/User.java
- 일정/기록 상세 조회 구현
- 반려동물별 일정 조회 구현
- 날짜별 일정/기록 전체 조회 구현
close #23
close #24 
close #25 
close #32
=> [Feat] 일정/기록 상세 조회 구현, 반려동물별 일정 조회 구현, 날짜별 일정/기록 전체 조회 구현 (#23, #24, #25, #32)

backend/src/main/java/com/hot6/backend/notification/NotificationController.java, backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java, backend/src/main/java/com/hot6/backend/notification/NotificationService.java, backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
=> [Feat] 알림 조회 삭제

backend/src/main/java/com/hot6/backend/notification/NotificationController.java, backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java, backend/src/main/java/com/hot6/backend/notification/NotificationService.java, backend/src/main/java/com/hot6/backend/notification/ScheduleNotificationScheduler.java, backend/src/main/java/com/hot6/backend/pet/PetController.java, backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java
=> [Fix] 오류 수정

backend/src/main/java/com/hot6/backend/board/answer/AnswerController.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/answer/images/AnswerImageRepository.java, backend/src/main/java/com/hot6/backend/board/comment/CommentController.java, backend/src/main/java/com/hot6/backend/board/comment/CommentService.java, backend/src/main/java/com/hot6/backend/board/hashtagQuestion/Hashtag_QuestionController.java, backend/src/main/java/com/hot6/backend/board/hashtagQuestion/Hashtag_QuestionService.java, backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
=> [Refactor] 서비스 전역 예외 처리 및 상태 코드 적용

backend/src/main/java/com/hot6/backend/category/CategoryService.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/common/exception/BaseException.java, backend/src/main/java/com/hot6/backend/notification/NotificationService.java, backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/pet/S3Service.java
=> [Fix] 오류 코드 커스텀

backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
=> [Fix] 오류 코드 겹침 해결

backend/src/main/java/com/hot6/backend/user/UserController.java, backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java
=> [Fix] 비밀번호 변경 기능

backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoom.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomHashtagRepository.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomParticipantRepository.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomHashtagService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomParticipantService.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
=> [Feat] 채팅방 정보 수정 (#15)

backend/src/main/java/com/hot6/backend/notification/ScheduleNotificationScheduler.java, backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
=> [Fix] 알림에 반려동물 이름 추가

backend/src/main/java/com/hot6/backend/user/UserController.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java
=> [Feat] 회원가입 입력 값 검증 로직 추가

backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java
=> [Fix] 회원가입시 기본 url 적용

backend/src/main/java/com/hot6/backend/pet/PetService.java, backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/resources/application.yml
=> [Fix] 펫 기본이미지 삽입

backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java, backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/common/exception/GlobalExceptionHandler.java
=> [Feat] 게시판 필수 입력 검증 추가

backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/Post.java
=> [Fix] 게시글, 댓글 cascade설정

backend/src/main/java/com/hot6/backend/board/comment/CommentService.java, backend/src/main/java/com/hot6/backend/board/comment/model/Comment.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java
=> [Fix] 트랜잭셔널 적용 수정

backend/src/main/java/com/hot6/backend/user/UserController.java, backend/src/main/java/com/hot6/backend/user/UserRepository.java, backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java
=> [Fix] 닉네임 수정

backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/model/Question.java
=> [Feat] Q&A 트랜잭셔널 수정

backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java
=> [Fix] AnswerService 수정

backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/comment/CommentRepository.java, backend/src/main/java/com/hot6/backend/board/comment/CommentService.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
=> [Feat] 게시판 최신순 내림차순 적용, 검색 기능 수정

backend/src/main/java/com/hot6/backend/notification/NotificationService.java
=> [Fix] 알림 트랙잭션 처리

backend/src/main/java/com/hot6/backend/config/CustomAuthFailureHandler.java, backend/src/main/java/com/hot6/backend/config/OAuth2FailureHandler.java, backend/src/main/java/com/hot6/backend/config/OAuth2SuccessHandler.java, backend/src/main/java/com/hot6/backend/config/SecurityConfig.java, backend/src/main/java/com/hot6/backend/config/filter/LoginFilter.java, backend/src/main/java/com/hot6/backend/user/OAuth2SuccessHandler.java, backend/src/main/java/com/hot6/backend/user/UserController.java, backend/src/main/java/com/hot6/backend/user/UserService.java, backend/src/main/java/com/hot6/backend/user/model/EmailVerify.java, backend/src/main/java/com/hot6/backend/user/model/User.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java, backend/src/main/resources/application.yml, backend/src/main/resources/data.sql
- 이메일 중복 확인 기능 구현
- 일반/소셜 회원 탈퇴 기능 구현
=> [Feat] 이메일 중복 확인 기능, 일반/소셜 회원 탈퇴 기능 구현

backend/src/main/java/com/hot6/backend/config/SecurityConfig.java
=> [Chore] security config actuator 추가

backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/Post.java, backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java
=> [Feat] 더미 데이터 삽입 세팅

backend/src/main/java/com/hot6/backend/config/CustomAuthFailureHandler.java, backend/src/main/java/com/hot6/backend/user/UserService.java
=> [Fix] 회원 로그인 에러 처리

backend/src/main/java/com/hot6/backend/board/post/PostController.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/post/model/PostListResponse.java, backend/src/main/java/com/hot6/backend/board/question/QuestionController.java, backend/src/main/java/com/hot6/backend/board/question/QuestionRepository.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java, backend/src/main/java/com/hot6/backend/board/question/model/Question.java, backend/src/main/java/com/hot6/backend/board/question/model/QuestionListResponse.java
=> [Fix] 게시판 페이징 수정

backend/src/main/java/com/hot6/backend/admin/AdminController.java, backend/src/main/java/com/hot6/backend/user/model/UserDto.java
=> [Fix] 관리자 페이지 찐찐막 수정

backend/src/main/java/com/hot6/backend/board/post/PostController.java
=> [Fix] 검색 기능 수정

backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java
=> [Fix] Repository 메서드 수정

backend/src/main/java/com/hot6/backend/config/SecurityConfig.java, backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java, backend/src/main/java/com/hot6/backend/schedule/model/ScheduleDto.java
=> [Feat] 장소 선택 기능 구현

backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java, backend/src/main/java/com/hot6/backend/schedule/ScheduleService.java
=> [Feat] 일정 반복 기능 구현

backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/question/QuestionRepository.java
=> [Fix] 답변 수 표시 수정

backend/src/main/java/com/hot6/backend/notification/NotificationController.java, backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java, backend/src/main/java/com/hot6/backend/notification/NotificationService.java, backend/src/main/java/com/hot6/backend/notification/model/Notification.java, backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
=> [Fix] 알림 뱃지 수정

backend/src/main/java/com/hot6/backend/admin/AdminController.java, backend/src/main/java/com/hot6/backend/chat/ChatController.java, backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoom.java, backend/src/main/java/com/hot6/backend/chat/model/ChatRoomType.java, backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepository.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java
=> [Feat] 관리자 채팅방 생성 및 조회

backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java, backend/src/main/java/com/hot6/backend/chat/service/ChatRoomService.java
=> [Fix] 채팅방 시간 외 접속 금지 및 인원수 조정

backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java, backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java, backend/src/main/java/com/hot6/backend/board/comment/CommentRepository.java, backend/src/main/java/com/hot6/backend/board/comment/CommentService.java, backend/src/main/java/com/hot6/backend/board/post/PostRepository.java, backend/src/main/java/com/hot6/backend/board/post/PostService.java, backend/src/main/java/com/hot6/backend/board/question/QuestionRepository.java, backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
=> [feat] 게시판 N+1 문제 해결

backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java, backend/src/main/java/com/hot6/backend/schedule/ScheduleService.java
=> [Fix] 알림 삭제 기능 구현
